[2021-03-15 20:30:48,544] {scheduler_job.py:154} INFO - Started process (PID=55886) to work on /home/alunoigti/airflow/dags/treino03.py
[2021-03-15 20:30:48,551] {scheduler_job.py:1589} INFO - Processing file /home/alunoigti/airflow/dags/treino03.py for tasks to queue
[2021-03-15 20:30:48,554] {logging_mixin.py:112} INFO - [2021-03-15 20:30:48,554] {dagbag.py:417} INFO - Filling up the DagBag from /home/alunoigti/airflow/dags/treino03.py
[2021-03-15 20:30:48,562] {logging_mixin.py:112} INFO - [2021-03-15 20:30:48,559] {dagbag.py:259} ERROR - Failed to import: /home/alunoigti/airflow/dags/treino03.py
Traceback (most recent call last):
  File "/home/alunoigti/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 256, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/home/alunoigti/anaconda3/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/alunoigti/airflow/dags/treino03.py", line 60
    def =pd.read_csv('usr/local/airflow/data/train.csv')
        ^
SyntaxError: invalid syntax
[2021-03-15 20:30:48,564] {scheduler_job.py:1603} WARNING - No viable dags retrieved from /home/alunoigti/airflow/dags/treino03.py
[2021-03-15 20:30:48,623] {scheduler_job.py:162} INFO - Processing /home/alunoigti/airflow/dags/treino03.py took 0.079 seconds
[2021-03-15 20:32:07,837] {scheduler_job.py:154} INFO - Started process (PID=56140) to work on /home/alunoigti/airflow/dags/treino03.py
[2021-03-15 20:32:07,841] {scheduler_job.py:1589} INFO - Processing file /home/alunoigti/airflow/dags/treino03.py for tasks to queue
[2021-03-15 20:32:07,842] {logging_mixin.py:112} INFO - [2021-03-15 20:32:07,842] {dagbag.py:417} INFO - Filling up the DagBag from /home/alunoigti/airflow/dags/treino03.py
[2021-03-15 20:32:07,845] {logging_mixin.py:112} INFO - [2021-03-15 20:32:07,844] {dagbag.py:259} ERROR - Failed to import: /home/alunoigti/airflow/dags/treino03.py
Traceback (most recent call last):
  File "/home/alunoigti/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 256, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/home/alunoigti/anaconda3/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/alunoigti/airflow/dags/treino03.py", line 60
    def =pd.read_csv('usr/local/airflow/data/train.csv')
        ^
SyntaxError: invalid syntax
[2021-03-15 20:32:07,847] {scheduler_job.py:1603} WARNING - No viable dags retrieved from /home/alunoigti/airflow/dags/treino03.py
[2021-03-15 20:32:07,875] {scheduler_job.py:162} INFO - Processing /home/alunoigti/airflow/dags/treino03.py took 0.037 seconds
[2021-03-15 20:33:27,258] {scheduler_job.py:154} INFO - Started process (PID=56393) to work on /home/alunoigti/airflow/dags/treino03.py
[2021-03-15 20:33:27,262] {scheduler_job.py:1589} INFO - Processing file /home/alunoigti/airflow/dags/treino03.py for tasks to queue
[2021-03-15 20:33:27,263] {logging_mixin.py:112} INFO - [2021-03-15 20:33:27,263] {dagbag.py:417} INFO - Filling up the DagBag from /home/alunoigti/airflow/dags/treino03.py
[2021-03-15 20:33:27,267] {logging_mixin.py:112} INFO - [2021-03-15 20:33:27,266] {dagbag.py:259} ERROR - Failed to import: /home/alunoigti/airflow/dags/treino03.py
Traceback (most recent call last):
  File "/home/alunoigti/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 256, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/home/alunoigti/anaconda3/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/alunoigti/airflow/dags/treino03.py", line 60
    def =pd.read_csv('usr/local/airflow/data/train.csv')
        ^
SyntaxError: invalid syntax
[2021-03-15 20:33:27,268] {scheduler_job.py:1603} WARNING - No viable dags retrieved from /home/alunoigti/airflow/dags/treino03.py
[2021-03-15 20:33:27,293] {scheduler_job.py:162} INFO - Processing /home/alunoigti/airflow/dags/treino03.py took 0.035 seconds
[2021-03-15 20:34:48,284] {scheduler_job.py:154} INFO - Started process (PID=56635) to work on /home/alunoigti/airflow/dags/treino03.py
[2021-03-15 20:34:48,288] {scheduler_job.py:1589} INFO - Processing file /home/alunoigti/airflow/dags/treino03.py for tasks to queue
[2021-03-15 20:34:48,290] {logging_mixin.py:112} INFO - [2021-03-15 20:34:48,290] {dagbag.py:417} INFO - Filling up the DagBag from /home/alunoigti/airflow/dags/treino03.py
[2021-03-15 20:34:48,293] {logging_mixin.py:112} INFO - [2021-03-15 20:34:48,292] {dagbag.py:259} ERROR - Failed to import: /home/alunoigti/airflow/dags/treino03.py
Traceback (most recent call last):
  File "/home/alunoigti/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 256, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/home/alunoigti/anaconda3/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/alunoigti/airflow/dags/treino03.py", line 60
    def =pd.read_csv('usr/local/airflow/data/train.csv')
        ^
SyntaxError: invalid syntax
[2021-03-15 20:34:48,294] {scheduler_job.py:1603} WARNING - No viable dags retrieved from /home/alunoigti/airflow/dags/treino03.py
[2021-03-15 20:34:48,334] {scheduler_job.py:162} INFO - Processing /home/alunoigti/airflow/dags/treino03.py took 0.050 seconds
[2021-03-15 20:53:22,652] {scheduler_job.py:154} INFO - Started process (PID=5292) to work on /home/alunoigti/airflow/dags/treino03.py
[2021-03-15 20:53:22,657] {scheduler_job.py:1589} INFO - Processing file /home/alunoigti/airflow/dags/treino03.py for tasks to queue
[2021-03-15 20:53:22,659] {logging_mixin.py:112} INFO - [2021-03-15 20:53:22,659] {dagbag.py:417} INFO - Filling up the DagBag from /home/alunoigti/airflow/dags/treino03.py
[2021-03-15 20:53:23,345] {scheduler_job.py:1601} INFO - DAG(s) dict_keys(['treino-03']) retrieved from /home/alunoigti/airflow/dags/treino03.py
[2021-03-15 20:53:23,362] {logging_mixin.py:112} INFO - [2021-03-15 20:53:23,362] {dag.py:1520} INFO - Creating ORM DAG for treino-03
[2021-03-15 20:53:23,402] {scheduler_job.py:162} INFO - Processing /home/alunoigti/airflow/dags/treino03.py took 0.750 seconds
[2021-03-15 20:55:02,845] {scheduler_job.py:154} INFO - Started process (PID=5588) to work on /home/alunoigti/airflow/dags/treino03.py
[2021-03-15 20:55:02,868] {scheduler_job.py:1589} INFO - Processing file /home/alunoigti/airflow/dags/treino03.py for tasks to queue
[2021-03-15 20:55:02,875] {logging_mixin.py:112} INFO - [2021-03-15 20:55:02,873] {dagbag.py:417} INFO - Filling up the DagBag from /home/alunoigti/airflow/dags/treino03.py
[2021-03-15 20:55:04,662] {scheduler_job.py:1601} INFO - DAG(s) dict_keys(['treino-03']) retrieved from /home/alunoigti/airflow/dags/treino03.py
[2021-03-15 20:55:04,716] {scheduler_job.py:162} INFO - Processing /home/alunoigti/airflow/dags/treino03.py took 1.871 seconds
[2021-03-15 20:56:26,846] {scheduler_job.py:154} INFO - Started process (PID=5854) to work on /home/alunoigti/airflow/dags/treino03.py
[2021-03-15 20:56:26,860] {scheduler_job.py:1589} INFO - Processing file /home/alunoigti/airflow/dags/treino03.py for tasks to queue
[2021-03-15 20:56:26,861] {logging_mixin.py:112} INFO - [2021-03-15 20:56:26,861] {dagbag.py:417} INFO - Filling up the DagBag from /home/alunoigti/airflow/dags/treino03.py
[2021-03-15 20:56:27,185] {scheduler_job.py:1601} INFO - DAG(s) dict_keys(['treino-03']) retrieved from /home/alunoigti/airflow/dags/treino03.py
[2021-03-15 20:56:27,249] {scheduler_job.py:1305} INFO - Processing treino-03
[2021-03-15 20:56:27,292] {scheduler_job.py:1315} INFO - Created <DagRun treino-03 @ 2021-03-15T23:50:00+00:00: scheduled__2021-03-15T23:50:00+00:00, externally triggered: False>
[2021-03-15 20:56:27,296] {scheduler_job.py:771} INFO - Examining DAG run <DagRun treino-03 @ 2021-03-15 23:50:00+00:00: scheduled__2021-03-15T23:50:00+00:00, externally triggered: False>
[2021-03-15 20:56:27,308] {scheduler_job.py:771} INFO - Examining DAG run <DagRun treino-03 @ 2021-03-15 23:55:12.998804+00:00: manual__2021-03-15T23:55:12.998804+00:00, externally triggered: True>
[2021-03-15 20:56:27,507] {scheduler_job.py:459} INFO - Skipping SLA check for <DAG: treino-03> because no tasks in DAG have SLAs
[2021-03-15 20:56:27,512] {scheduler_job.py:1668} INFO - Creating / updating <TaskInstance: treino-03.get_data 2021-03-15 23:50:00+00:00 [scheduled]> in ORM
[2021-03-15 20:56:27,517] {scheduler_job.py:1668} INFO - Creating / updating <TaskInstance: treino-03.get_data 2021-03-15 23:55:12.998804+00:00 [scheduled]> in ORM
[2021-03-15 20:56:27,543] {scheduler_job.py:162} INFO - Processing /home/alunoigti/airflow/dags/treino03.py took 0.697 seconds
[2021-03-15 20:58:05,456] {scheduler_job.py:154} INFO - Started process (PID=6143) to work on /home/alunoigti/airflow/dags/treino03.py
[2021-03-15 20:58:05,463] {scheduler_job.py:1589} INFO - Processing file /home/alunoigti/airflow/dags/treino03.py for tasks to queue
[2021-03-15 20:58:05,468] {logging_mixin.py:112} INFO - [2021-03-15 20:58:05,468] {dagbag.py:417} INFO - Filling up the DagBag from /home/alunoigti/airflow/dags/treino03.py
[2021-03-15 20:58:06,712] {scheduler_job.py:1601} INFO - DAG(s) dict_keys(['treino-03']) retrieved from /home/alunoigti/airflow/dags/treino03.py
[2021-03-15 20:58:06,833] {scheduler_job.py:1305} INFO - Processing treino-03
[2021-03-15 20:58:06,972] {scheduler_job.py:1315} INFO - Created <DagRun treino-03 @ 2021-03-15 23:52:00+00:00: scheduled__2021-03-15T23:52:00+00:00, externally triggered: False>
[2021-03-15 20:58:06,989] {scheduler_job.py:771} INFO - Examining DAG run <DagRun treino-03 @ 2021-03-15 23:50:00+00:00: scheduled__2021-03-15T23:50:00+00:00, externally triggered: False>
[2021-03-15 20:58:07,309] {scheduler_job.py:771} INFO - Examining DAG run <DagRun treino-03 @ 2021-03-15 23:52:00+00:00: scheduled__2021-03-15T23:52:00+00:00, externally triggered: False>
[2021-03-15 20:58:07,403] {scheduler_job.py:771} INFO - Examining DAG run <DagRun treino-03 @ 2021-03-15 23:55:12.998804+00:00: manual__2021-03-15T23:55:12.998804+00:00, externally triggered: True>
[2021-03-15 20:58:07,938] {scheduler_job.py:459} INFO - Skipping SLA check for <DAG: treino-03> because no tasks in DAG have SLAs
[2021-03-15 20:58:07,961] {scheduler_job.py:1668} INFO - Creating / updating <TaskInstance: treino-03.get_data 2021-03-15 23:50:00+00:00 [scheduled]> in ORM
[2021-03-15 20:58:07,977] {scheduler_job.py:1668} INFO - Creating / updating <TaskInstance: treino-03.get_data 2021-03-15 23:52:00+00:00 [scheduled]> in ORM
[2021-03-15 20:58:07,999] {scheduler_job.py:1668} INFO - Creating / updating <TaskInstance: treino-03.get_data 2021-03-15 23:55:12.998804+00:00 [scheduled]> in ORM
[2021-03-15 20:58:08,029] {scheduler_job.py:162} INFO - Processing /home/alunoigti/airflow/dags/treino03.py took 2.575 seconds
